import type { Metadata } from 'next'
import './globals.css'
import React from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#with-tailwind-css
// Add antialiased to body with font

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-2xl text-white">{children}</body>
    </html>
  )
}
